import { SchemeRule } from "./types";

export const MOSJE_SCHEMES: SchemeRule[] = [
  {
    id: "mosje-msy",
    name: "Mahila Samriddhi Yojana (MSY)",
    code: "MSY",
    category: "WOMEN_EMPOWERMENT",
    targetGroup: "SC_WOMEN",
    maxProjectCost: 140000,
    maxAnnualIncome: 500000,
    interestRateMin: 4.0,
    interestRateMax: 4.0,
    repaymentTenureYears: 3,
    moratoriumMonths: 3,
    fundingBreakdown: {
      nsfdcSharePercent: 90,
      channelPartnerSharePercent: 10,
      promoterContributionPercent: 0,
      maxSubsidyAmount: 10000,
    },
    keyBenefits: [
      "Ultra-concessional 4% interest rate per annum",
      "Tailored specifically for Scheduled Caste women entrepreneurs",
      "Zero promoter contribution required",
    ],
    eligibleActivities: [
      "Tailoring and garment fabrication",
      "Beauty and wellness centers",
      "Food preparation and confectionery",
      "Handicrafts and artisanal goods",
    ],
  },
  {
    id: "mosje-els",
    name: "Educational Loan Scheme (ELS)",
    code: "ELS",
    category: "EDUCATION",
    targetGroup: "SC_STUDENTS",
    maxProjectCost: 3000000,
    maxAnnualIncome: 500000,
    interestRateMin: 4.0,
    interestRateMax: 4.5,
    repaymentTenureYears: 5,
    moratoriumMonths: 12,
    fundingBreakdown: {
      nsfdcSharePercent: 90,
      channelPartnerSharePercent: 10,
      promoterContributionPercent: 0,
    },
    keyBenefits: [
      "Up to Rs. 20 Lakhs in India and Rs. 30 Lakhs abroad",
      "Course duration plus 6 months repayment moratorium",
      "Concessional 4% rate for female students (4.5% for male)",
    ],
    eligibleActivities: [
      "Professional engineering degrees",
      "Medical and nursing qualifications",
      "Management and business administration",
      "Accredited post-graduate studies overseas",
    ],
  },
  {
    id: "mosje-mcf",
    name: "Micro Credit Finance Scheme (MCF)",
    code: "MCF",
    category: "MICRO_FINANCE",
    targetGroup: "ALL_SC",
    maxProjectCost: 140000,
    maxAnnualIncome: 500000,
    interestRateMin: 5.0,
    interestRateMax: 6.5,
    repaymentTenureYears: 3,
    moratoriumMonths: 3,
    fundingBreakdown: {
      nsfdcSharePercent: 90,
      channelPartnerSharePercent: 10,
      promoterContributionPercent: 0,
    },
    keyBenefits: [
      "Up to 90% NSFDC loan assistance",
      "Zero promoter margin required for small projects",
      "Swift processing through local Channel Partners",
    ],
    eligibleActivities: [
      "Retail kiosk and grocery shops",
      "Dairy farming and animal husbandry",
      "Mobile repair and electronic service centers",
      "Fruit and vegetable trading",
    ],
  },
  {
    id: "mosje-term-loan",
    name: "NSFDC Term Loan Scheme",
    code: "TERM_LOAN",
    category: "TERM_LOAN",
    targetGroup: "ALL_SC",
    maxProjectCost: 5000000,
    maxAnnualIncome: 500000,
    interestRateMin: 6.5,
    interestRateMax: 8.0,
    repaymentTenureYears: 10,
    moratoriumMonths: 6,
    fundingBreakdown: {
      nsfdcSharePercent: 90,
      channelPartnerSharePercent: 5,
      promoterContributionPercent: 5,
    },
    keyBenefits: [
      "Substantial capital assistance up to Rs. 50.00 Lakhs",
      "Long repayment horizon up to 10 years",
      "6-month moratorium for initial establishment",
    ],
    eligibleActivities: [
      "Small-scale manufacturing facilities",
      "Commercial transport and logistics operations",
      "Agro-processing and cold storage units",
      "Service and hospitality enterprises",
    ],
  },
];
