import { DistrictHub, ChannelPartner } from "./types";

export const DISTRICT_HUBS: DistrictHub[] = [
  { id: "lucknow", name: "Lucknow", state: "Uttar Pradesh", coordinates: { lat: 26.8467, lng: 80.9462 } },
  { id: "delhi", name: "New Delhi", state: "Delhi NCR", coordinates: { lat: 28.6139, lng: 77.209 } },
  { id: "patna", name: "Patna", state: "Bihar", coordinates: { lat: 25.5941, lng: 85.1376 } },
  { id: "jaipur", name: "Jaipur", state: "Rajasthan", coordinates: { lat: 26.9124, lng: 75.7873 } },
  { id: "mumbai", name: "Mumbai", state: "Maharashtra", coordinates: { lat: 19.076, lng: 72.8777 } },
  { id: "bhopal", name: "Bhopal", state: "Madhya Pradesh", coordinates: { lat: 23.2599, lng: 77.4126 } },
  { id: "bengaluru", name: "Bengaluru", state: "Karnataka", coordinates: { lat: 12.9716, lng: 77.5946 } },
  { id: "chennai", name: "Chennai", state: "Tamil Nadu", coordinates: { lat: 13.0827, lng: 80.2707 } },
  { id: "kolkata", name: "Kolkata", state: "West Bengal", coordinates: { lat: 22.5726, lng: 88.3639 } },
  { id: "hyderabad", name: "Hyderabad", state: "Telangana", coordinates: { lat: 17.385, lng: 78.4867 } },
  { id: "ahmedabad", name: "Ahmedabad", state: "Gujarat", coordinates: { lat: 23.0225, lng: 72.5714 } },
  { id: "raipur", name: "Raipur", state: "Chhattisgarh", coordinates: { lat: 21.2514, lng: 81.6296 } },
  { id: "ranchi", name: "Ranchi", state: "Jharkhand", coordinates: { lat: 23.3441, lng: 85.3096 } },
  { id: "guwahati", name: "Guwahati", state: "Assam", coordinates: { lat: 26.1445, lng: 91.7362 } },
  { id: "chandigarh", name: "Chandigarh", state: "Punjab", coordinates: { lat: 30.7333, lng: 76.7794 } },
];

export const PRESEEDED_PARTNERS: ChannelPartner[] = [
  // --- Lucknow, UP ---
  {
    id: "lko-sca-01",
    name: "UP Scheduled Castes Finance & Development Corp (UPSCFDC)",
    institutionType: "SCA",
    branchName: "Hazratganj Central SCA Office",
    state: "Uttar Pradesh",
    district: "Lucknow",
    address: "Bapu Bhawan Commercial Complex, Hazratganj, Lucknow",
    coordinates: { lat: 26.8485, lng: 80.9455 },
    contactPhone: "+91-522-2238450",
    nodalOfficer: "Shri R. K. Gautam (General Manager)",
    npaPercentage: 2.4,
    overdueRate: 3.1,
    remainingQuotaLakhs: 85.0,
    averageTurnaroundDays: 14,
    supportedSchemes: ["MCF", "TERM_LOAN", "MSY", "ELS"],
    healthScore: 94,
    healthTier: "SOLVENT",
  },
  {
    id: "lko-psb-01",
    name: "Punjab National Bank",
    institutionType: "PSB",
    branchName: "Ashok Marg Nodal Branch",
    state: "Uttar Pradesh",
    district: "Lucknow",
    address: "18 Ashok Marg, Near Shakti Bhawan, Lucknow",
    coordinates: { lat: 26.852, lng: 80.942 },
    contactPhone: "+91-522-2287102",
    nodalOfficer: "Smt. Sunita Verma (Chief Manager Credit)",
    npaPercentage: 3.8,
    overdueRate: 4.5,
    remainingQuotaLakhs: 140.0,
    averageTurnaroundDays: 16,
    supportedSchemes: ["MCF", "TERM_LOAN", "MSY"],
    healthScore: 87,
    healthTier: "SOLVENT",
  },
  {
    id: "lko-rrb-01",
    name: "Aryavart Bank (RRB)",
    institutionType: "RRB",
    branchName: "Alambagh Regional Branch",
    state: "Uttar Pradesh",
    district: "Lucknow",
    address: "Singar Nagar, Alambagh, Lucknow",
    coordinates: { lat: 26.815, lng: 80.902 },
    contactPhone: "+91-522-2451920",
    nodalOfficer: "Shri Anil Kumar Maurya (Branch Head)",
    npaPercentage: 6.2,
    overdueRate: 7.0,
    remainingQuotaLakhs: 45.0,
    averageTurnaroundDays: 22,
    supportedSchemes: ["MCF", "MSY"],
    healthScore: 68,
    healthTier: "MODERATE",
  },
  {
    id: "lko-psb-02",
    name: "Bank of Baroda",
    institutionType: "PSB",
    branchName: "Chowk Heritage Branch",
    state: "Uttar Pradesh",
    district: "Lucknow",
    address: "Victoria Street, Chowk, Lucknow",
    coordinates: { lat: 26.868, lng: 80.904 },
    contactPhone: "+91-522-2256190",
    nodalOfficer: "Shri Deepanker Sen (Senior Manager)",
    npaPercentage: 12.8, // High-NPA branch (should be filtered out)
    overdueRate: 15.2,
    remainingQuotaLakhs: 0.0, // Depleted quota
    averageTurnaroundDays: 38,
    supportedSchemes: ["MCF", "TERM_LOAN"],
    healthScore: 32,
    healthTier: "HIGH_RISK",
  },

  // --- New Delhi / NCR ---
  {
    id: "del-sca-01",
    name: "Delhi SC/ST/OBC/Minorities Development Corp (DSFDC)",
    institutionType: "SCA",
    branchName: "Ambedkar Bhawan Head Office",
    state: "Delhi NCR",
    district: "New Delhi",
    address: "2 Battery Lane, Rajpur Road, Civil Lines, Delhi",
    coordinates: { lat: 28.672, lng: 77.224 },
    contactPhone: "+91-11-23932801",
    nodalOfficer: "Dr. P. L. Meena (Executive Director)",
    npaPercentage: 2.1,
    overdueRate: 2.8,
    remainingQuotaLakhs: 210.0,
    averageTurnaroundDays: 12,
    supportedSchemes: ["MCF", "TERM_LOAN", "MSY", "ELS"],
    healthScore: 96,
    healthTier: "SOLVENT",
  },
  {
    id: "del-psb-01",
    name: "State Bank of India",
    institutionType: "PSB",
    branchName: "Parliament Street SME Branch",
    state: "Delhi NCR",
    district: "New Delhi",
    address: "11 Parliament Street, Connaught Place, New Delhi",
    coordinates: { lat: 28.625, lng: 77.214 },
    contactPhone: "+91-11-23374900",
    nodalOfficer: "Shri Vikramaditya Das (Assistant General Manager)",
    npaPercentage: 3.2,
    overdueRate: 3.9,
    remainingQuotaLakhs: 350.0,
    averageTurnaroundDays: 15,
    supportedSchemes: ["MCF", "TERM_LOAN", "ELS"],
    healthScore: 91,
    healthTier: "SOLVENT",
  },
  {
    id: "del-nbfc-01",
    name: "Margdarshak Financial Services (NBFC-MFI)",
    institutionType: "NBFC_MFI",
    branchName: "Okhla Industrial Micro Hub",
    state: "Delhi NCR",
    district: "New Delhi",
    address: "Phase-III Okhla Industrial Area, New Delhi",
    coordinates: { lat: 28.535, lng: 77.272 },
    contactPhone: "+91-11-41618290",
    nodalOfficer: "Smt. Priyanka Tiwari (Regional Credit Lead)",
    npaPercentage: 7.4,
    overdueRate: 8.2,
    remainingQuotaLakhs: 60.0,
    averageTurnaroundDays: 19,
    supportedSchemes: ["MCF", "MSY"],
    healthScore: 64,
    healthTier: "MODERATE",
  },

  // --- Patna, Bihar ---
  {
    id: "pat-sca-01",
    name: "Bihar State SC Co-op Development Corp (BSSCDC)",
    institutionType: "SCA",
    branchName: "Vidyapati Marg State Branch",
    state: "Bihar",
    district: "Patna",
    address: "Vidyapati Marg, Near Kotwali, Patna",
    coordinates: { lat: 25.602, lng: 85.132 },
    contactPhone: "+91-612-2223841",
    nodalOfficer: "Shri Manoj Paswan (Managing Director)",
    npaPercentage: 3.5,
    overdueRate: 4.2,
    remainingQuotaLakhs: 95.0,
    averageTurnaroundDays: 18,
    supportedSchemes: ["MCF", "TERM_LOAN", "MSY", "ELS"],
    healthScore: 89,
    healthTier: "SOLVENT",
  },
  {
    id: "pat-rrb-01",
    name: "Dakshin Bihar Gramin Bank",
    institutionType: "RRB",
    branchName: "Kankarbagh Commercial Branch",
    state: "Bihar",
    district: "Patna",
    address: "Old Bypass Road, Kankarbagh, Patna",
    coordinates: { lat: 25.588, lng: 85.154 },
    contactPhone: "+91-612-2358911",
    nodalOfficer: "Shri S. K. Singh (Branch Head)",
    npaPercentage: 5.8,
    overdueRate: 6.9,
    remainingQuotaLakhs: 50.0,
    averageTurnaroundDays: 20,
    supportedSchemes: ["MCF", "MSY"],
    healthScore: 71,
    healthTier: "MODERATE",
  },
  {
    id: "pat-psb-01",
    name: "Central Bank of India",
    institutionType: "PSB",
    branchName: "Frazer Road Branch",
    state: "Bihar",
    district: "Patna",
    address: "Dak Bungalow Crossing, Frazer Road, Patna",
    coordinates: { lat: 25.609, lng: 85.136 },
    contactPhone: "+91-612-2231490",
    nodalOfficer: "Shri Alok Ranjan (Credit Manager)",
    npaPercentage: 11.5,
    overdueRate: 13.8,
    remainingQuotaLakhs: 15.0,
    averageTurnaroundDays: 34,
    supportedSchemes: ["MCF", "TERM_LOAN"],
    healthScore: 39,
    healthTier: "HIGH_RISK",
  },

  // --- Jaipur, Rajasthan ---
  {
    id: "jai-sca-01",
    name: "Rajasthan SC & ST Finance & Development Co-op (Anuprati)",
    institutionType: "SCA",
    branchName: "Nehru Sahkar Bhawan Office",
    state: "Rajasthan",
    district: "Jaipur",
    address: "22 Godam Circle, Sahkar Marg, Jaipur",
    coordinates: { lat: 26.899, lng: 75.792 },
    contactPhone: "+91-141-2741980",
    nodalOfficer: "Shri Hemant Bairwa (General Manager)",
    npaPercentage: 2.8,
    overdueRate: 3.4,
    remainingQuotaLakhs: 110.0,
    averageTurnaroundDays: 15,
    supportedSchemes: ["MCF", "TERM_LOAN", "MSY", "ELS"],
    healthScore: 92,
    healthTier: "SOLVENT",
  },
  {
    id: "jai-rrb-01",
    name: "Rajasthan Marudhara Gramin Bank (RMGB)",
    institutionType: "RRB",
    branchName: "M.I. Road Commercial Office",
    state: "Rajasthan",
    district: "Jaipur",
    address: "Mirza Ismail Road, Jayanti Market, Jaipur",
    coordinates: { lat: 26.918, lng: 75.808 },
    contactPhone: "+91-141-2365821",
    nodalOfficer: "Smt. Manju Meghwal (Senior Branch Manager)",
    npaPercentage: 4.1,
    overdueRate: 4.8,
    remainingQuotaLakhs: 75.0,
    averageTurnaroundDays: 17,
    supportedSchemes: ["MCF", "MSY"],
    healthScore: 84,
    healthTier: "SOLVENT",
  },

  // --- Mumbai, Maharashtra ---
  {
    id: "mum-sca-01",
    name: "Mahatma Phule Backward Class Development Corp (MPBCDC)",
    institutionType: "SCA",
    branchName: "Bandra Kurla Complex Division",
    state: "Maharashtra",
    district: "Mumbai",
    address: "Pinnacle Corporate Park, BKC Bandra East, Mumbai",
    coordinates: { lat: 19.066, lng: 72.868 },
    contactPhone: "+91-22-26591240",
    nodalOfficer: "Shri Nitin Kamble (Managing Director)",
    npaPercentage: 1.9,
    overdueRate: 2.4,
    remainingQuotaLakhs: 320.0,
    averageTurnaroundDays: 11,
    supportedSchemes: ["MCF", "TERM_LOAN", "MSY", "ELS"],
    healthScore: 97,
    healthTier: "SOLVENT",
  },
  {
    id: "mum-psb-01",
    name: "Bank of India",
    institutionType: "PSB",
    branchName: "Fort Commercial Branch",
    state: "Maharashtra",
    district: "Mumbai",
    address: "M.G. Road, Fort, Mumbai",
    coordinates: { lat: 18.932, lng: 72.833 },
    contactPhone: "+91-22-22678900",
    nodalOfficer: "Shri Arvind Sawant (Chief Manager)",
    npaPercentage: 3.6,
    overdueRate: 4.1,
    remainingQuotaLakhs: 280.0,
    averageTurnaroundDays: 14,
    supportedSchemes: ["MCF", "TERM_LOAN", "ELS"],
    healthScore: 90,
    healthTier: "SOLVENT",
  },

  // --- Bhopal, Madhya Pradesh ---
  {
    id: "bho-sca-01",
    name: "MP State SC Finance & Development Corp",
    institutionType: "SCA",
    branchName: "Vallabh Bhawan Headquarters",
    state: "Madhya Pradesh",
    district: "Bhopal",
    address: "Arera Hills, Near Mantralaya, Bhopal",
    coordinates: { lat: 23.242, lng: 77.425 },
    contactPhone: "+91-755-2551820",
    nodalOfficer: "Shri Rajesh Malviya (Joint Commissioner)",
    npaPercentage: 3.1,
    overdueRate: 3.7,
    remainingQuotaLakhs: 90.0,
    averageTurnaroundDays: 16,
    supportedSchemes: ["MCF", "TERM_LOAN", "MSY", "ELS"],
    healthScore: 91,
    healthTier: "SOLVENT",
  },
  {
    id: "bho-rrb-01",
    name: "Madhyanchal Gramin Bank",
    institutionType: "RRB",
    branchName: "MP Nagar Zone-II Branch",
    state: "Madhya Pradesh",
    district: "Bhopal",
    address: "Maharana Pratap Nagar, Bhopal",
    coordinates: { lat: 23.235, lng: 77.438 },
    contactPhone: "+91-755-2761890",
    nodalOfficer: "Shri Kamal Kishor (Branch Manager)",
    npaPercentage: 6.8,
    overdueRate: 7.5,
    remainingQuotaLakhs: 40.0,
    averageTurnaroundDays: 21,
    supportedSchemes: ["MCF", "MSY"],
    healthScore: 66,
    healthTier: "MODERATE",
  },

  // --- Bengaluru, Karnataka ---
  {
    id: "blr-sca-01",
    name: "Dr. B.R. Ambedkar Development Corp Ltd",
    institutionType: "SCA",
    branchName: "Vidhana Soudha Central SCA",
    state: "Karnataka",
    district: "Bengaluru",
    address: "Vishveshwaraiah Towers, Dr. Ambedkar Veedhi, Bengaluru",
    coordinates: { lat: 12.979, lng: 77.591 },
    contactPhone: "+91-80-22864510",
    nodalOfficer: "Dr. H. M. Revanna (Managing Director)",
    npaPercentage: 2.2,
    overdueRate: 2.9,
    remainingQuotaLakhs: 190.0,
    averageTurnaroundDays: 13,
    supportedSchemes: ["MCF", "TERM_LOAN", "MSY", "ELS"],
    healthScore: 95,
    healthTier: "SOLVENT",
  },
  {
    id: "blr-psb-01",
    name: "Canara Bank",
    institutionType: "PSB",
    branchName: "Town Hall SME Hub",
    state: "Karnataka",
    district: "Bengaluru",
    address: "J.C. Road, Near Town Hall, Bengaluru",
    coordinates: { lat: 12.965, lng: 77.585 },
    contactPhone: "+91-80-22221940",
    nodalOfficer: "Smt. Shailaja Murthy (Assistant General Manager)",
    npaPercentage: 3.4,
    overdueRate: 4.0,
    remainingQuotaLakhs: 240.0,
    averageTurnaroundDays: 15,
    supportedSchemes: ["MCF", "TERM_LOAN", "ELS"],
    healthScore: 89,
    healthTier: "SOLVENT",
  },

  // --- Chennai, Tamil Nadu ---
  {
    id: "chn-sca-01",
    name: "Tamil Nadu Adi Dravidar Housing & Dev Corp (TAHDCO)",
    institutionType: "SCA",
    branchName: "Nandanam Divisional Office",
    state: "Tamil Nadu",
    district: "Chennai",
    address: "Cenotaph Road, Teynampet, Chennai",
    coordinates: { lat: 13.032, lng: 80.245 },
    contactPhone: "+91-44-24345102",
    nodalOfficer: "Thiru K. Ilango (Executive Director)",
    npaPercentage: 2.5,
    overdueRate: 3.2,
    remainingQuotaLakhs: 160.0,
    averageTurnaroundDays: 14,
    supportedSchemes: ["MCF", "TERM_LOAN", "MSY", "ELS"],
    healthScore: 93,
    healthTier: "SOLVENT",
  },
  {
    id: "chn-psb-01",
    name: "Indian Overseas Bank",
    institutionType: "PSB",
    branchName: "Mount Road Central Branch",
    state: "Tamil Nadu",
    district: "Chennai",
    address: "763 Anna Salai, Chennai",
    coordinates: { lat: 13.061, lng: 80.261 },
    contactPhone: "+91-44-28524180",
    nodalOfficer: "Smt. Geetha Sundaram (Senior Manager)",
    npaPercentage: 4.2,
    overdueRate: 4.9,
    remainingQuotaLakhs: 180.0,
    averageTurnaroundDays: 16,
    supportedSchemes: ["MCF", "TERM_LOAN", "MSY"],
    healthScore: 85,
    healthTier: "SOLVENT",
  },

  // --- Kolkata, West Bengal ---
  {
    id: "kol-sca-01",
    name: "West Bengal SC/ST Development & Finance Corp",
    institutionType: "SCA",
    branchName: "Salt Lake Sector-I Office",
    state: "West Bengal",
    district: "Kolkata",
    address: "CF-361, Salt Lake City, Sector-I, Kolkata",
    coordinates: { lat: 22.586, lng: 88.408 },
    contactPhone: "+91-33-23348120",
    nodalOfficer: "Shri Debasish Roy (Managing Director)",
    npaPercentage: 3.3,
    overdueRate: 4.1,
    remainingQuotaLakhs: 120.0,
    averageTurnaroundDays: 15,
    supportedSchemes: ["MCF", "TERM_LOAN", "MSY", "ELS"],
    healthScore: 90,
    healthTier: "SOLVENT",
  },
  {
    id: "kol-psb-01",
    name: "UCO Bank",
    institutionType: "PSB",
    branchName: "B.T.M. Sarani Head Office",
    state: "West Bengal",
    district: "Kolkata",
    address: "10 Brabourne Road, Kolkata",
    coordinates: { lat: 22.578, lng: 88.351 },
    contactPhone: "+91-33-22254120",
    nodalOfficer: "Shri Sourav Banerjee (Chief Credit Manager)",
    npaPercentage: 13.4, // High-NPA branch
    overdueRate: 16.0,
    remainingQuotaLakhs: 0.0,
    averageTurnaroundDays: 42,
    supportedSchemes: ["MCF", "TERM_LOAN"],
    healthScore: 28,
    healthTier: "HIGH_RISK",
  },

  // --- Hyderabad, Telangana ---
  {
    id: "hyd-sca-01",
    name: "Telangana Scheduled Castes Co-op Development Corp",
    institutionType: "SCA",
    branchName: "Masab Tank Central Office",
    state: "Telangana",
    district: "Hyderabad",
    address: "Damodaram Sanjeevaiah Sankshema Bhavan, Masab Tank, Hyderabad",
    coordinates: { lat: 17.405, lng: 78.452 },
    contactPhone: "+91-40-23391820",
    nodalOfficer: "Dr. E. Sreedhar (Managing Director)",
    npaPercentage: 2.3,
    overdueRate: 3.0,
    remainingQuotaLakhs: 175.0,
    averageTurnaroundDays: 13,
    supportedSchemes: ["MCF", "TERM_LOAN", "MSY", "ELS"],
    healthScore: 94,
    healthTier: "SOLVENT",
  },
  {
    id: "hyd-psb-01",
    name: "Union Bank of India",
    institutionType: "PSB",
    branchName: "Koti Commercial Branch",
    state: "Telangana",
    district: "Hyderabad",
    address: "Turrebaz Khan Road, Koti, Hyderabad",
    coordinates: { lat: 17.387, lng: 78.484 },
    contactPhone: "+91-40-24651920",
    nodalOfficer: "Shri K. Venkat Rao (Chief Manager)",
    npaPercentage: 4.5,
    overdueRate: 5.1,
    remainingQuotaLakhs: 130.0,
    averageTurnaroundDays: 17,
    supportedSchemes: ["MCF", "TERM_LOAN", "MSY"],
    healthScore: 83,
    healthTier: "SOLVENT",
  },

  // --- Ahmedabad, Gujarat ---
  {
    id: "ahm-sca-01",
    name: "Gujarat Scheduled Castes Development Corp (GSCDC)",
    institutionType: "SCA",
    branchName: "Ashram Road Division",
    state: "Gujarat",
    district: "Ahmedabad",
    address: "Dr. Babasaheb Ambedkar Bhavan, Ashram Road, Ahmedabad",
    coordinates: { lat: 23.036, lng: 72.571 },
    contactPhone: "+91-79-26581900",
    nodalOfficer: "Shri J. M. Solanki (General Manager)",
    npaPercentage: 2.7,
    overdueRate: 3.3,
    remainingQuotaLakhs: 115.0,
    averageTurnaroundDays: 14,
    supportedSchemes: ["MCF", "TERM_LOAN", "MSY", "ELS"],
    healthScore: 92,
    healthTier: "SOLVENT",
  },

  // --- Raipur, Chhattisgarh ---
  {
    id: "rai-sca-01",
    name: "Chhattisgarh Antyavasayi Co-op Finance Corp",
    institutionType: "SCA",
    branchName: "Telibandha Headquarters",
    state: "Chhattisgarh",
    district: "Raipur",
    address: "VIP Road, Telibandha, Raipur",
    coordinates: { lat: 21.238, lng: 81.672 },
    contactPhone: "+91-771-2441920",
    nodalOfficer: "Shri P. R. Tande (Managing Director)",
    npaPercentage: 3.9,
    overdueRate: 4.7,
    remainingQuotaLakhs: 65.0,
    averageTurnaroundDays: 17,
    supportedSchemes: ["MCF", "TERM_LOAN", "MSY"],
    healthScore: 86,
    healthTier: "SOLVENT",
  },

  // --- Ranchi, Jharkhand ---
  {
    id: "ran-sca-01",
    name: "Jharkhand State SC Co-op Development Corp",
    institutionType: "SCA",
    branchName: "Harmu Housing Colony Branch",
    state: "Jharkhand",
    district: "Ranchi",
    address: "Harmu Housing Colony, Argora, Ranchi",
    coordinates: { lat: 23.352, lng: 85.312 },
    contactPhone: "+91-651-2245190",
    nodalOfficer: "Shri Manoj Ram (Executive Officer)",
    npaPercentage: 4.8,
    overdueRate: 5.6,
    remainingQuotaLakhs: 55.0,
    averageTurnaroundDays: 18,
    supportedSchemes: ["MCF", "TERM_LOAN", "MSY", "ELS"],
    healthScore: 82,
    healthTier: "SOLVENT",
  },

  // --- Guwahati, Assam ---
  {
    id: "guw-sca-01",
    name: "Assam State Development Corp for Scheduled Castes",
    institutionType: "SCA",
    branchName: "Dispur Capital Office",
    state: "Assam",
    district: "Guwahati",
    address: "G.S. Road, Dispur, Guwahati",
    coordinates: { lat: 26.141, lng: 91.789 },
    contactPhone: "+91-361-2231940",
    nodalOfficer: "Dr. B. K. Das (Director)",
    npaPercentage: 4.4,
    overdueRate: 5.3,
    remainingQuotaLakhs: 70.0,
    averageTurnaroundDays: 19,
    supportedSchemes: ["MCF", "TERM_LOAN", "MSY"],
    healthScore: 84,
    healthTier: "SOLVENT",
  },

  // --- Chandigarh, Punjab ---
  {
    id: "chd-sca-01",
    name: "Punjab Scheduled Castes Land Dev & Finance Corp (PSCFC)",
    institutionType: "SCA",
    branchName: "Sector-17 City Center",
    state: "Punjab",
    district: "Chandigarh",
    address: "SCO 112-113, Bank Square, Sector-17B, Chandigarh",
    coordinates: { lat: 30.738, lng: 76.782 },
    contactPhone: "+91-172-2704190",
    nodalOfficer: "Shri Harpreet Singh (General Manager)",
    npaPercentage: 2.6,
    overdueRate: 3.1,
    remainingQuotaLakhs: 130.0,
    averageTurnaroundDays: 13,
    supportedSchemes: ["MCF", "TERM_LOAN", "MSY", "ELS"],
    healthScore: 93,
    healthTier: "SOLVENT",
  },
];
