import { BeneficiaryLead } from "./types";

export const PRESEEDED_LEADS: BeneficiaryLead[] = [
  {
    id: "lead-01",
    applicationId: "SETU-2026-LKO-8492",
    applicantName: "Smt. Rekha Devi",
    casteCategory: "Scheduled Caste (SC)",
    annualIncome: 180000,
    enterpriseActivity: "Garment Tailoring & Fabrication Unit",
    schemeCode: "MSY",
    schemeName: "Mahila Samriddhi Yojana (MSY)",
    projectCost: 140000,
    concessionalAmount: 126000,
    monthlyEmi: 3721,
    designatedBranchId: "lko-sca-01",
    designatedBranchName: "UP Scheduled Castes Finance Corp (Hazratganj)",
    status: "DOCUMENTS_VERIFIED",
    submissionDate: "2026-09-01T10:30:00Z",
    verifiedDate: "2026-09-02T14:15:00Z",
    remarks: "Tehsildar caste and income certificate verified. Awaiting credit committee sanction.",
  },
  {
    id: "lead-02",
    applicationId: "SETU-2026-PAT-3921",
    applicantName: "Shri Rameshwar Paswan",
    casteCategory: "Scheduled Caste (SC)",
    annualIncome: 160000,
    enterpriseActivity: "Small-Scale Agro Processing & Packaging",
    schemeCode: "MCF",
    schemeName: "Micro Credit Finance (MCF)",
    projectCost: 155000,
    concessionalAmount: 139500,
    monthlyEmi: 4210,
    designatedBranchId: "pat-sca-01",
    designatedBranchName: "Bihar State SC Co-op Dev Corp (Patna)",
    status: "CREDIT_SANCTIONED",
    submissionDate: "2026-08-28T11:00:00Z",
    verifiedDate: "2026-08-29T15:20:00Z",
    sanctionedDate: "2026-09-01T16:45:00Z",
    remarks: "Sanction letter issued. Disbursal scheduled upon promissory note execution.",
  },
  {
    id: "lead-03",
    applicationId: "SETU-2026-DEL-1044",
    applicantName: "Kumari Kavita Jatav",
    casteCategory: "Scheduled Caste (SC)",
    annualIncome: 240000,
    enterpriseActivity: "Higher Professional Technical Degree (B.Tech)",
    schemeCode: "ELS",
    schemeName: "Educational Loan Scheme (ELS)",
    projectCost: 500000,
    concessionalAmount: 450000,
    monthlyEmi: 5310,
    designatedBranchId: "del-psb-01",
    designatedBranchName: "State Bank of India (Parliament Street)",
    status: "PRE_SCREENED",
    submissionDate: "2026-09-02T09:15:00Z",
    remarks: "Pre-screened via voice assistant. Applicant to submit bonafide college admission certificate.",
  },
  {
    id: "lead-04",
    applicationId: "SETU-2026-JAI-7729",
    applicantName: "Shri Vijay Kumar",
    casteCategory: "Scheduled Caste (SC)",
    annualIncome: 320000,
    enterpriseActivity: "Automotive Repair & Spare Parts Workshop",
    schemeCode: "TERM_LOAN",
    schemeName: "Term Loan Scheme (TLS)",
    projectCost: 550000,
    concessionalAmount: 495000,
    monthlyEmi: 9940,
    designatedBranchId: "jai-sca-01",
    designatedBranchName: "Rajasthan SC & ST Finance Co-op (Jaipur)",
    status: "PRE_SCREENED",
    submissionDate: "2026-09-02T13:40:00Z",
    remarks: "Project feasibility quotation uploaded. Awaiting physical branch document submission.",
  },
  {
    id: "lead-05",
    applicationId: "SETU-2026-MUM-6102",
    applicantName: "Smt. Meena Kamble",
    casteCategory: "Scheduled Caste (SC)",
    annualIncome: 140000,
    enterpriseActivity: "Sanitary Products Manufacturing & Micro-Retail",
    schemeCode: "MSY",
    schemeName: "Mahila Samriddhi Yojana (MSY)",
    projectCost: 110000,
    concessionalAmount: 99000,
    monthlyEmi: 2920,
    designatedBranchId: "mum-sca-01",
    designatedBranchName: "Mahatma Phule Backward Class Dev Corp (Mumbai)",
    status: "DISBURSED",
    submissionDate: "2026-08-20T10:00:00Z",
    verifiedDate: "2026-08-22T11:30:00Z",
    sanctionedDate: "2026-08-25T14:00:00Z",
    disbursedDate: "2026-08-28T17:00:00Z",
    remarks: "Disbursement completed via Direct Benefit Transfer (DBT) to beneficiary account.",
  },
  {
    id: "lead-06",
    applicationId: "SETU-2026-BHO-4411",
    applicantName: "Shri Ajay Malviya",
    casteCategory: "Scheduled Caste (SC)",
    annualIncome: 190000,
    enterpriseActivity: "Dairy Farming & Milk Chilling Center",
    schemeCode: "MCF",
    schemeName: "Micro Credit Finance (MCF)",
    projectCost: 150000,
    concessionalAmount: 135000,
    monthlyEmi: 4070,
    designatedBranchId: "bho-rrb-01",
    designatedBranchName: "Madhyanchal Gramin Bank (Bhopal)",
    status: "DOCUMENTS_VERIFIED",
    submissionDate: "2026-08-30T14:20:00Z",
    verifiedDate: "2026-09-01T12:00:00Z",
    remarks: "Livestock purchase estimate and shed lease deed verified by field officer.",
  },
  {
    id: "lead-07",
    applicationId: "SETU-2026-BLR-8930",
    applicantName: "Smt. Shanthi Revanna",
    casteCategory: "Scheduled Caste (SC)",
    annualIncome: 210000,
    enterpriseActivity: "Silk Weaving & Handloom Handicrafts",
    schemeCode: "MSY",
    schemeName: "Mahila Samriddhi Yojana (MSY)",
    projectCost: 140000,
    concessionalAmount: 126000,
    monthlyEmi: 3721,
    designatedBranchId: "blr-sca-01",
    designatedBranchName: "Dr. B.R. Ambedkar Dev Corp (Bengaluru)",
    status: "CREDIT_SANCTIONED",
    submissionDate: "2026-08-26T09:40:00Z",
    verifiedDate: "2026-08-28T16:10:00Z",
    sanctionedDate: "2026-08-31T15:30:00Z",
    remarks: "Sanctioned under special women entrepreneur allocation. Ready for DBT transfer.",
  },
  {
    id: "lead-08",
    applicationId: "SETU-2026-CHN-5509",
    applicantName: "Shri Thiru Murugan",
    casteCategory: "Scheduled Caste (SC)",
    annualIncome: 380000,
    enterpriseActivity: "Commercial Light Motor Vehicle (Cargo Transport)",
    schemeCode: "TERM_LOAN",
    schemeName: "Term Loan Scheme (TLS)",
    projectCost: 800000,
    concessionalAmount: 720000,
    monthlyEmi: 14460,
    designatedBranchId: "chn-sca-01",
    designatedBranchName: "TAHDCO Central Office (Chennai)",
    status: "PRE_SCREENED",
    submissionDate: "2026-09-02T16:15:00Z",
    remarks: "Commercial driving license and dealer quotation uploaded.",
  },
  {
    id: "lead-09",
    applicationId: "SETU-2026-KOL-2180",
    applicantName: "Shri Debasish Sardar",
    casteCategory: "Scheduled Caste (SC)",
    annualIncome: 150000,
    enterpriseActivity: "Leather Goods & Footwear Fabrication",
    schemeCode: "MCF",
    schemeName: "Micro Credit Finance (MCF)",
    projectCost: 140000,
    concessionalAmount: 126000,
    monthlyEmi: 3800,
    designatedBranchId: "kol-sca-01",
    designatedBranchName: "West Bengal SC/ST Dev Corp (Kolkata)",
    status: "DISBURSED",
    submissionDate: "2026-08-15T11:20:00Z",
    verifiedDate: "2026-08-18T10:00:00Z",
    sanctionedDate: "2026-08-21T14:30:00Z",
    disbursedDate: "2026-08-25T16:00:00Z",
    remarks: "Fully disbursed and operational unit confirmed via geotagged photo audit.",
  },
  {
    id: "lead-10",
    applicationId: "SETU-2026-CHD-9023",
    applicantName: "Shri Harpreet Ram",
    casteCategory: "Scheduled Caste (SC)",
    annualIncome: 260000,
    enterpriseActivity: "Master of Computer Applications (MCA)",
    schemeCode: "ELS",
    schemeName: "Educational Loan Scheme (ELS)",
    projectCost: 400000,
    concessionalAmount: 360000,
    monthlyEmi: 4250,
    designatedBranchId: "chd-sca-01",
    designatedBranchName: "Punjab SC Land Dev & Finance Corp (Chandigarh)",
    status: "DOCUMENTS_VERIFIED",
    submissionDate: "2026-09-01T15:00:00Z",
    verifiedDate: "2026-09-02T16:45:00Z",
    remarks: "Academic merit and entrance scorecard verified. Credit sanction pending.",
  },
];
